# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2025-present Datadog, Inc.
name: "Test Action"
on:
  pull_request:
  push:
    branches:
      - main
      - "release/*"
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day

jobs:
  test-upload:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload reports
        uses: ./
        with:
          api_key: ${{ secrets.DD_API_KEY_CI_VISIBILITY }}
          ignored-paths: "**/subfolder"

  test-pinned-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload reports with pinned datadog-ci version
        uses: ./
        with:
          api_key: ${{ secrets.DD_API_KEY_CI_VISIBILITY }}
          version: "v5.6.0"

  test-should-complain-about-missing-api-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload reports without API key
        uses: ./
        id: test_step
        continue-on-error: true
      - name: Check that previous step failed
        if: steps.test_step.outcome == 'success'
        run: |
          echo "The previous step did not fail as expected"
          exit 1
