name: 'Test Action'
on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  test:
    strategy:
      matrix:
        version: [14, 16, 18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload reports using a glob pattern
        uses: ./
        with:
          api_key: ${{secrets.DD_API_KEY_CI_VISIBILITY}}
          ignored-paths: '**/subfolder'
          node-version: ${{ matrix.version}}
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY_CI_VISIBILITY }}

  test-should-complain-about-missing-api-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload reports using a glob pattern
        uses: ./
        id: test_step
        with:
        continue-on-error: true
      - name: Check that previous step failed
        if: steps.test_step.outcome == 'success'
        run: |
          echo "The previous step did not fail as expected"
          exit 1
